### ISSUE TITLE
math expressions not rendered, custom fonts not loaded 

### ISSUE THREAD

**Issue by DavidWiesner** [bugra/bugra.github.com#1]
Hi,
thanks for your Blog https://bugra.github.io !

I have discovered some issues when visiting your blog via https. So for example in the article [Alternating Least Squares Method for Collaborative Filtering](https://bugra.github.io/work/notes/2014-04-19/alternating-least-squares-method-for-collaborative-filtering/) the math-expression won't get rendered. The problem is some scripts are loaded with their http-URL. What is blocked by some browsers. So in this example 'MathJax.js' and `d3js` won't get loaded. 
To solve this issue just replace all `<script src="http://...` with `<script src="https://...`

regards,
David

**Comment by bugra** [comment]
Hi,
Thanks for letting me know about this problem. I fixed this issue with https://github.com/bugra/bugra.github.com/commit/82b07674dc1a83c5f6f5a7b1be33e38ce147bc31 
Please, let me know if you have further issues.

Cheers,
Bugra
